config/routes.rb
Rails.application.routes.draw do

  root  to: "splash#index"
  get "/about",        to: "about#show"

  get "/signup",        to: "users#new"
  get "/login",         to: "sessions#new"
  get "/logout",        to: "sessions#destroy"


  post "/sessions/demo",to: "sessions#demo", as: "demo"
  post "/sessions",     to: "sessions#create", as: "sessions"

  post "/users", to: "users#create", as: "users"

  post "/unit/:unit_id/chore/:chore_id/reassign", to: "user_chores#reassign", as: "reassign", :collection => { :user_id => :put }

  post "/unit/:unit_id/user/:user_id/state", to: "unit_users#create", as: "state"
  delete "/unit/:unit_id/user/:user_id/state", to: "unit_users#destroy"
  patch "/unit/:unit_id/user/:user_id/state", to: "unit_users#update"

  patch "/units/:unit_id/chores/:chore_id/user_chores", to: "user_chores#update", as: "user_chores"
  patch "/units/:unit_id/date", to: "user_chores#change_date", as: "date"


  resources :units do
    resources :users, shallow: true
    resources :chores, shallow: true
    resources :user_chores, only: [:edit,:update]
  end


end

app/models/unit.rb
class Unit < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :address, presence: true, uniqueness: true

  def slug
   name.downcase.gsub(" ", "-")
  end

 def to_param
   "#{id}-#{slug}"
 end

  has_many :unit_users
  has_many :users, through: :unit_users
  has_many :chores, through: :users
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
    if state(@unit, current_user) == "approved"
      render :show
    else
      flash[:error] = "Oops! You need to join a unit in order to view it!"
      redirect_to units_path
    end
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  # def edit
  #   if state(@unit, current_user) == "approved"
  #     render :edit
  #   else
  #     flash[:error] = "Oops! You need to join a unit in order to view it!"
  #     redirect_to units_path
  #   end
  # end

  # POST /units
  # POST /units.json
  def create
    if current_user
    @unit = Unit.new(unit_params)
      name = @unit.name
      @unit.users << current_user
      current_user.units.each do |unit|
        if state(unit,current_user) === "approved"
          flash[:error] = "You are already a amember of unit #{unit.name}. You must deactivate to create a new unit."
          return redirect_to units_path
        end
      end
      if @unit.save
        change_state(@unit,current_user,"approved")
        flash[:notice] = "#{@unit.name} was saved."
        return redirect_to unit_path(@unit)
      else
        flash[:notice] = "#{name} failed to update."
        return redirect_to new_unit_path
      end
    else
      return redirect_to root_path
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    if state(@unit,current_user) === "approved"
      if @unit.update(unit_params)
        flash[:notice] = "#{@unit.name} was successfully updated"
        return redirect_to unit_path(@unit)
      else
        flash[:error] = "#{@unit.name} failed to update"
        return redirect_to edit_unit_path(@unit)
      end
    else
      flash[:error] = "Unauthorized"
      return redirect_to units_path
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  # def destroy
  #   if state(@unit, current_user) == "approved"
  #     name = @unit.name
  #     @unit = Unit.find
  #     if @unit.destroy
  #       flash[:notice] = "#{name} was destroyed"
  #       redirect_to units_path
  #     else
  #       flash[:notice] = "#{name} persists"
  #       redirect_to unit_path(@unit)
  #     end
  #   else
  #     flash[:notice] = "I'm sorry, you do not have permission to do that!"
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name, :address, :landlord_name, :landlord_phone, :landlord_email)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= form_for(unit) do |f| %>
  <% if unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<fieldset>
  <div class="control-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="control-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="control-group">
    <%= f.label :landlord_name %><br>
    <%= f.text_field :landlord_name, class: "form-control" %>
  </div>
  <div class="control-group">
    <%= f.label :landlord_phone %><br>
    <%= f.text_field :landlord_phone, class: "form-control" %>
  </div>
  <div class="control-group">
    <%= f.label :landlord_email %><br>
    <%= f.text_field :landlord_email, class: "form-control" %>
  </div>
  <div class="control-actions">
    <%= f.submit class: "btn btn-default" %>
  </div>
</fieldset>

<% end %>

app/views/units/edit.html.erb
<h1>Editing Unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<h1>Listing Units</h1>
<%= link_to 'Create Unit', new_unit_path, class: "btn btn-danger btn-md"%>
<ul class="list-group">

<% @units.each do |unit| %>
  <li class="list-group-item"> <%= link_to unit.name, unit_path(unit) %>
    <% if (state(unit,current_user) === nil || state(unit,current_user) === "blank") %>
      <%= link_to "Join", state_path(unit, current_user, state: "pending"), html_options={method: :post, class: "pull-right"} %>
    <% end %>
    <% if state(unit,current_user) === "pending" %>
      <%= link_to "Remove", state_path(unit, current_user, state: "removed"), html_options={method: :delete, class: "pull-right"} %>
    <% end %>
  </li>

<% end %>

</ul>

app/views/units/new.html.erb
<h1>New Unit</h1>
<%= link_to 'Units Page', units_path, class: "btn btn-danger btn-md" %>
<%= render partial: 'form', locals: {unit: @unit} %>

app/views/units/show.html.erb
<p id="notice" role="status" aria-live="assertive"><%= notice %></p>

<div class="row main">
  <div id="chores-link" class="col-sm-6 col-sm-offset-3">
    <%=link_to "Chores", unit_chores_path(@unit), html_options = {role:"link",class: "btn btn-warning btn-block"}%>
  </div>
</div>
<div class="row">
    <h3 aria-level="2" class="main">Roommates</h3>
      <hr aria-hidden="true">

    <% @unit.users.each do |roommate| %>
    <% if state(@unit,roommate) === "approved" %>
    <div class="col-sm-6">


    <div class="app panel-primary main" role="article" aria-label="<%= roommate.name %> details">

      <h3 role="heading" aria-level="3" class="panel-heading">
        <%= roommate.name %>
      </h3>

      <div class="panel-body">
        <div class="col-xs-3">
          <img id="user-photo-<%= roommate.id %>" class="img-responsive img-circle" alt="profile picture for <%=roommate.name%>" src= <%=roommate.photo%> >
        </div>
        <div class="col-xs-9" id="user-info-<%= roommate.id %>">
          <p>
            <strong>Email:</strong>
            <%= roommate.email %>
          </p>

          <p>
            <strong>Phone:</strong>
            <%= roommate.phone %>
          </p>

          <p>
            <strong>Chores:</strong>
            <% roommate.chores.each do |chore| %>
              <%= "#{chore.title}, " %>
            <% end %>
          </p>
          <% if roommate == current_user %>
          <div class="row">
            <button role="button" class="btn btn-danger text-btn col-xs-6 col-lg-4"> <%= link_to "Leave Unit", user_path(roommate), method: :delete%> </button>
            <button data-toggle="modal" data-target="#modal_user_<%=roommate.id%>_edit" class="text-btn modal-btn btn btn-warning col-xs-6 col-lg-4" role="button">Edit User</button>
          </div>
          <% end %>
        </div>
      </div>
    </div>



    <div id="modal_user_<%=roommate.id%>_edit" class="modal fade" role="dialog">
      <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close modal-close" aria-label="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Edit <%=roommate.name%>'s Profile</h4>
          </div>
          <div class="modal-body">
            <%= render partial: 'users/form', locals: {user: roommate}%>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default modal-close" data-dismiss="modal">Close</button>
          </div>
        </div>

      </div>
    </div>


</div>
  <% end %>
  <% end %>

</div>

<% if any_pending?(@unit) %>
<div class="row main">
<div id="pending-user" class="col-sm-6">
  <hr aria-hidden="true">
  <h3 aria-level="2">Pending Roommates</h3>
  <hr aria-hidden="true">

  <div id="pendingListDesc" class="hidden">
    Approve or deny pending roommates to your unit.
  </div>
  <ul class="list-group" aria-describedby="pendingListDesc">
    <% @unit.users.each do |roommate| %>
    <% if state(@unit,roommate) === "pending" %>
    <li class="list-group-item pending-list-item">
      <div class="row">
        <span class="pending-user-name col-xs-4 col-lg-6"><%= roommate.name %></span>
        <span class="col-xs-8 col-lg-6">
          <button role="button" class="btn text-btn btn-success col-xs-6"><%= link_to "Approve", state_path(@unit, roommate, state: "approved"), html_options={method: :patch} %></button>
          <button role="button" class="btn text-btn btn-danger col-xs-6"><%= link_to "Decline", state_path(@unit, roommate, state: "blocked"), html_options={method: :patch} %></button>
        </span>
      </div>
    </li>

    <% end %>
    <% end %>

  </ul>
</div>

</div>

<% end %>

<div class="main">
  <button data-toggle="modal" data-target="#modal_unit_edit" class="text-btn modal-btn btn btn-warning" role="button">Edit Unit</button>
  <span class="btn text-btn btn-primary"><%= link_to 'All Units', units_path %></span>
</div>

<div id="modal_unit_edit" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close modal-close" aria-label="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
        <%= render partial: 'form', locals: {unit: @unit}%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default modal-close" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

<footer class="navbar navbar-inverse main">
  <div class="text-center">
    <p>
      <%= @unit.name %> | <%= @unit.address %>
    </p>

    <p>
      <strong>Landlord Contact:</strong>
      <%= @unit.landlord_name %> |
      <%= @unit.landlord_phone %> |
      <%= @unit.landlord_email %>
    </p>
  </div>
</footer>