config/routes.rb
Rails.application.routes.draw do

  root  to: "splash#index"
  get "/about",        to: "about#show"

  get "/signup",        to: "users#new"
  get "/login",         to: "sessions#new"
  get "/logout",        to: "sessions#destroy"


  post "/sessions/demo",to: "sessions#demo", as: "demo"
  post "/sessions",     to: "sessions#create", as: "sessions"

  post "/users", to: "users#create", as: "users"

  post "/unit/:unit_id/chore/:chore_id/reassign", to: "user_chores#reassign", as: "reassign", :collection => { :user_id => :put }

  post "/unit/:unit_id/user/:user_id/state", to: "unit_users#create", as: "state"
  delete "/unit/:unit_id/user/:user_id/state", to: "unit_users#destroy"
  patch "/unit/:unit_id/user/:user_id/state", to: "unit_users#update"

  patch "/units/:unit_id/chores/:chore_id/user_chores", to: "user_chores#update", as: "user_chores"
  patch "/units/:unit_id/date", to: "user_chores#change_date", as: "date"


  resources :units do
    resources :users, shallow: true
    resources :chores, shallow: true
    resources :user_chores, only: [:edit,:update]
  end


end

app/models/chore.rb
class Chore < ActiveRecord::Base
  validates :title, presence: true
  validates :details, presence: true

  def slug
   title.downcase.gsub(" ", "-")
  end

 def to_param
   "#{id}-#{slug}"
 end

  has_many :user_chores, dependent: :destroy
  has_many :users, through: :user_chores


  def complete?
    UserChore.where(chore_id: self.id).first.completed
  end
  
end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
  before_action :set_unit, only: [:index, :create, :new]
  before_action :set_chore, only: [:show, :edit, :update, :destroy]
  before_action :set_approved_users, only: [:index]

  # GET /chores
  def index
    @new_chore = Chore.new
    @chores = []
    @unit.chores.each do |chore|
      if chore_of_unit?(chore,@unit) && !@chores.include?(chore)
        @chores << chore
      end
    end
    @chore = @chores.first
    if @chores.count > 0
      @user_chore = UserChore.where(chore_id: @chore.id).first
      @date_user_chore = @user_chore
    else
      @user_chore = UserChore.new
      @chore = Chore.new
    end
    render :index
  end


  # GET /chores/new
  def new
    @chore = Chore.new
    @user_chore = UserChore.new
  end

  # GET /chores/1/edit
  def edit
    @unit
    @chore.users.first.units.each do |unit|
      if chore_of_unit?(@chore,unit)
        @unit = unit
      end
    end

  end

  # POST /chores
  # POST /chores.json
  def create
    @chore = Chore.new(chore_params)

    deadline = nil
    if @unit.chores.count > 0
      @unit.chores.each do |chore|
        if chore_of_unit?(chore,@unit)
          deadline = UserChore.where(chore_id: chore.id).first.due_date
          break
        end
      end
    end

    if params[:user_chore][:user_id][0].blank?
      flash[:error] = "Chore must be assigned to someone."
      return redirect_to new_unit_chore_path(@unit)
    elsif @chore.save
      params[:user_chore][:user_id].each { |num| if !num.blank? then User.find(num.to_i).chores << @chore end}

      if deadline.nil?
        deadline = Time.at(Time.now.to_i + 604800)
      end

      UserChore.where(chore_id: @chore.id).update_all({completed: false, due_date: deadline})
      flash[:notice] = "#{@chore.title} was successfully updated."
    else
      flash[:error] = "Woops! It seems you're forgetting something! Please enter a valid title and details before submitting a chore."
    end
    redirect_to unit_chores_path(@unit)
  end


  #############Need to also update date

  # PATCH/PUT /chores/1
  # PATCH/PUT /chores/1.json
  def update
    @unit
    puts("CHORE: #{@chore}")
    @chore.users.first.units.each do |unit|
      if chore_of_unit?(@chore,unit)
        @unit = unit
      end
    end
    @chore.update(chore_params)
    redirect_to unit_chores_path(@unit)
  end

  # DELETE /chores/1
  # DELETE /chores/1.json
  def destroy
    @unit
    @chore.users.first.units.each do |unit|
      if chore_of_unit?(@chore,unit)
        @unit = unit
      end
    end
    @chore.destroy
    redirect_to unit_chores_path(@unit)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:unit_id])
    end

    def set_chore
      @chore = Chore.find(params[:id])
    end

    def set_approved_users
      @approved_users = []
      @unit.users.each do |user|
        if state(@unit,user) === "approved"
          @approved_users << user
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chore_params
      params.require(:chore).permit(:title, :details)
    end

    def user_chore_params
      params.require(:user_chore).permit(:user_id)
    end
end

app/helpers/chores_helper.rb
module ChoresHelper
end

app/views/chores/_edit_date.html.erb
<%= form_for @date_user_chore, url: date_path(@unit) do |f| %>


  <% if @date_user_chore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chore.errors.count, "error") %> prohibited this chore from being saved:</h2>

      <ul>
      <% @date_user_chore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<fieldset>
  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_field :due_date, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Update Due Date", class: "btn btn-default" %>
  </div>
</fieldset>
<% end %>

app/views/chores/_edit_form.html.erb
<%= form_for chore, url: (params[:action] == "new" ? unit_chores_path(@unit, chore) : chore), html: { class: "form-group" } do |f| %>

  <% if chore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chore.errors.count, "error") %> prohibited this chore from being saved:</h2>

      <ul>
      <% chore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<fieldset>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control", id: "chore_edit_title_#{chore.title}" %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_field :details, class: "form-control", id: "chore_edit_details_#{chore.title}" %>
  </div>
  <div class="actions">
    <%= f.submit "Update Chore", class: "btn btn-default" %>
  </div>
</fieldset>
<% end %>

app/views/chores/_form.html.erb
<%= form_for @user_chore, url: unit_chores_path(@unit, @user_chore) do |f| %>

  <% if @user_chore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_chore.errors.count, "error") %> prohibited this chore from being saved:</h2>

      <ul>
      <% @user_chore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>

  <%= fields_for chore do |ch| %>
  <div class="field">
    <%=ch.label :title %><br>
    <%=ch.text_field :title, class: "form-control" %>
  </div>
  <div class="field">
    <%=ch.label :details %></br>
    <%=ch.text_field  :details, class: "form-control" %>
  </div>
  <% end %>

<label>Roommates Responsible:</label>
  <div class="field">
    <%= f.collection_check_boxes :user_id, @approved_users, :id, :name do |b| %>
    <div class="collection_check_box">
      <%= b.check_box %>
      <%= b.label %>
    </div>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit "Create Chore", class: "btn btn-default" %>
  </div>

</fieldset>
<% end %>

app/views/chores/_reassign.html.erb
<% @user_chore = UserChore.new %>

<%= form_for @user_chore, url: reassign_path(@unit,chore,@user_chore), html: { id: "reassign_chore_#{chore.id}" } do |f| %>

  <% if @user_chore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_chore.errors.count, "error") %> prohibited this chore from being saved:</h2>

      <ul>
      <% @user_chore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <label>Roommates Responsible:</label>
  <% user_ids = [] %>
  <% chore.users.each { |user| user_ids << user.id} %>

<fieldset>
  <div class="field">
    <%= f.collection_check_boxes :user_id, @approved_users, :id, :name do |b| %>
    <div class="collection_check_box">
      <% if user_ids.include?(b.value) %>
        <%= b.check_box options = {:checked => true, id: "reassing_chore_#{chore.id}_user_#{b.value}"} %>
      <% else %>
        <%= b.check_box options = {:checked => false, id: "reassing_chore_#{chore.id}_user_#{b.value}"} %>
      <% end %>
      <%= b.label %>
    </div>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit "Reassign", class: "btn btn-default" %>
  </div>
</fieldset>
<% end %>

app/views/chores/edit.html.erb
<!-- <h1>Editing Chore</h1>

<%#= render 'form' %>

<%#= link_to 'Back', unit_chores_path(@unit) %> -->

app/views/chores/index.html.erb
<div class="row main">
  <div class="col-sm-6 col-sm-offset-3">
    <button tabindex="0" type="button" name="button" data-toggle="modal" data-target="#modal_new_chore" class="btn btn-success new-chore btn-block modal-btn">New Chore</button>
  </div>
</div>
<% if @chores.count > 0 %>
<span class="date_header main">
  <h1 aria-level="2">Due Date: <%= @user_chore.due_date.strftime("%B %d, %Y") %></h1>
  <button type="button" name="button" data-toggle="modal" data-target="#modal_date" class="btn btn-warning modal-btn">Edit Date</button>
</span>


<div class="row">
  <div class="col-sm-6">
    <h4 aria-level="2" class="main">To Do</h4>
    <hr aria-hidden="true">

    <% @chores.each do |chore| %>
    <% if !chore.complete? %>
    <% if chore_of_unit?(chore, @unit) %>

    <article class="app panel-primary main" role="article" aria-label="chore">

      <div class="panel-heading">
        <h3 role="heading" aria-level="3" class="chore-title"><%= chore.title %></h3>
        <div class="btn-group pull-right">
          <button tabindex="0" type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" aria-label="options">
            <span class="glyphicon glyphicon-menu-down"></span>
          </button>
          <ul class="dropdown-menu">
            <li> <a tabindex="0" class="btn btn-warning modal-btn" type="button" name="button"  data-toggle="modal" data-target="#modal_edit_<%=chore.id%>">Edit</a> </li>
            <li><%= link_to 'Destroy', chore, html_options={class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' }} %></li>
          </ul>
        </div>
      </div>

      <div class="panel-body">
        <p class="">
          Description: <%= chore.details %>
        </p>
        <p>
          Responsible:
          <% chore.users.each do |user| %>
          <%= " #{user.name}," %>
          <% end %>
        </p>
        <!-- <div class="btn-group"> -->
          <%= link_to "Completed", user_chores_path(@unit,chore, :completed => true), html_options={role:"button", class: "btn btn-success", method: :patch} %>
          <button class="btn btn-warning modal-btn" type="button" name="button"  data-toggle="modal" data-target="#modal_reassign_<%=chore.id%>">Reassign</button>
        <!-- </div> -->
      </div>
    <!-- </div> -->
  </article>


  <div id="modal_edit_<%=chore.id%>" class="modal fade" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" aria-label="close" class="close" data-dismiss="modal">&times;</button>
          <h4 id="edit_<%=chore.title%>" class="modal-title">Edit Chore</h4>
        </div>
        <div class="modal-body">
          <%= render partial: "edit_form", locals: {chore: chore} %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default modal-close" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>


  <div id="modal_reassign_<%=chore.id%>" class="modal fade" role="dialog" tabindex="-1">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" aria-label="close" class="close modal-close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Reassign Chores</h4>
        </div>
        <div class="modal-body">
          <%= render partial: "reassign", locals: {chore: chore} %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default modal-close" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>

  <% end %>
  <% end %>
  <% end %>
</div>

<div class="col-sm-6">
  <h4 aria-level="2" class="main">Finished</h4>
  <hr aria-hidden="true">
  <% @chores.each do |chore| %>
  <% if chore.complete? %>
  <% if chore_of_unit?(chore,@unit) %>
  <article class="app panel-primary main" role="article" aria-label="chore">
    <div class="panel-heading">
      <h3 id="chore_header_<%= chore.id %>" role="heading" class="chore-title"><%= chore.title %></h3>
      <div id="chore_dropdown_group_<%= chore.id %>" class="btn-group pull-right">
        <button aria-label="options" type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="glyphicon glyphicon-menu-down"></span>
        </button>
        <ul role="menu" class="dropdown-menu">
          <li> <a tabindex="0" class="btn btn-warning modal-btn" type="button" name="button" role="menuitem" data-toggle="modal" data-target="#modal_edit_<%=chore.id%>">Edit</a> </li>
          <li><%= link_to 'Destroy', chore, html_options={role:"menuitem",tabindex:"0",class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' }} %></li>
        </ul>
      </div>
    </div>

    <div class="panel-body">
      <p class="">
        Description: <%= chore.details %>
      </p>
      <p>
        Responsible:
        <% chore.users.each do |user| %>
        <%= " #{user.name},"%>
        <% end %>
      </p>
      <!-- <div class="btn-group" role="group"> -->
        <%= link_to "Incomplete", user_chores_path(@unit,chore, :completed => false), html_options={class: "btn btn-danger", method: :patch, role: "button"} %>
        <button class="btn btn-warning modal-btn" type="button" data-toggle="modal" data-target="#modal_reassign_<%=chore.id%>">Reassign</button>
      <!-- </div> -->
    </div>
  </article>

  <div id="modal_edit_<%=chore.id%>" class="modal fade" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close modal-close" aria-label="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Edit Chore</h4>
        </div>
        <div class="modal-body">
          <%= render partial: "edit_form", locals: {chore: chore} %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default modal-close" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>


  <div id="modal_reassign_<%=chore.id%>" class="modal fade" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close modal-close" aria-label="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Reassign Chores</h4>
        </div>
        <div class="modal-body">
          <%= render partial: "reassign", locals: {chore: chore} %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default modal-close" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>
  <% end %>
  <% end %>
  <% end %>
</div>

</div>

<!-- <hr> -->


<div id="modal_date" class="modal fade" role="dialog" tabindex="-1">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" aria-label="close" class="close modal-close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Edit Date</h4>
      </div>
      <div class="modal-body">
        <%= render partial: 'edit_date'%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default modal-close" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

<% end %>
<div id="modal_new_chore" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close modal-close" aria-label="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Create Chore</h4>
      </div>
      <div class="modal-body">
        <%= render partial: 'form', locals: {chore: @new_chore}%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default modal-close" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
</div>

app/views/chores/new.html.erb
<!-- <h1>New Chore</h1>

<%#= render 'form' %>

<%#= link_to 'Back', unit_chores_path %> -->