config/routes.rb
Rails.application.routes.draw do

  root  to: "splash#index"
  get "/about",        to: "about#show"

  get "/signup",        to: "users#new"
  get "/login",         to: "sessions#new"
  get "/logout",        to: "sessions#destroy"


  post "/sessions/demo",to: "sessions#demo", as: "demo"
  post "/sessions",     to: "sessions#create", as: "sessions"

  post "/users", to: "users#create", as: "users"

  post "/unit/:unit_id/chore/:chore_id/reassign", to: "user_chores#reassign", as: "reassign", :collection => { :user_id => :put }

  post "/unit/:unit_id/user/:user_id/state", to: "unit_users#create", as: "state"
  delete "/unit/:unit_id/user/:user_id/state", to: "unit_users#destroy"
  patch "/unit/:unit_id/user/:user_id/state", to: "unit_users#update"

  patch "/units/:unit_id/chores/:chore_id/user_chores", to: "user_chores#update", as: "user_chores"
  patch "/units/:unit_id/date", to: "user_chores#change_date", as: "date"


  resources :units do
    resources :users, shallow: true
    resources :chores, shallow: true
    resources :user_chores, only: [:edit,:update]
  end


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CHŌRUS</title>
    <%= favicon_link_tag 'luma.ico' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="A happy house is a clean house. Keep track of all the chores in your house in one place.">
    <meta name="author" content="Arthur Tonelli">
    <meta name="keywords" content="HTML,Accessibility,CSS,Ruby,Rails">


    <!-- Latest compiled and minified CSS -->
    <!-- <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/css/bootstrap.min.css" rel="stylesheet"/> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <script   src="https://code.jquery.com/ui/1.12.0-rc.2/jquery-ui.min.js"   integrity="sha256-55Jz3pBCF8z9jBO1qQ7cIf0L+neuPTD1u7Ytzrp2dqo="   crossorigin="anonymous"></script>
    <!-- <link href="//cdnjs.cloudflare.com/ajax/libs/bootcards/1.1.1/css/bootcards-ios.min.css" rel="stylesheet"> -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>

  <body style="padding-top: 0px">
    <a href="#main" class="skip-link main">main content</a>
    <nav class="navbar navbar-default main">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <%= link_to "CHŌRUS", root_path, class: "btn btn-primary brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "ABOUT", about_path, class: "btn btn-warning" %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li><%= link_to "Log-Out", logout_path, class: "btn btn-danger" %></li>
              <% if unit_of_user(current_user) %>
              <li><%= link_to "My Unit", unit_path(unit_of_user(current_user)), class: "btn btn-warning" %></li>
              <li><%= link_to "My Chores", unit_chores_path(unit_of_user(current_user)), class: "btn btn-primary" %></li>
              <% else %>
              <li><%= link_to "Units", units_path, class: "btn btn-info" %></li>
              <% end %>
            <% else %>
              <li><%= button_to "Demo Log-In", sessions_path(:user => {email: "john.doe@demo.com", password:"1234"}), class: "btn btn-warning"%></li>
              <li><%= link_to "Sign-Up", signup_path, class: "btn btn-primary"%></li>
              <li><%= link_to "Log-In", login_path, class: "btn btn-success"%></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <% if notice %>
    <div class="alert alert-info alert-dismissible main" role="alert" id="notice">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <strong>Notice:</strong><%= notice %>
    </div>
    <% end %>

    <% if flash[:error] %>
    <div class="alert alert-danger alert-dismissible main" role="alert" id="error">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <strong>Error:</strong><%= flash[:error] %>
    </div>
    <% end %>

    <main id="main" class="" tabindex="-1">
    <% if params[:controller] != "splash" %>
    <div class="container">
    <% end %>

      <%= yield %>

    <% if params[:controller] != "splash" %>
    </div>
    <% end %>
  </main>

<script src="https://cdn.accesslint.com/accesslint-1.1.2.js" type="text/javascript"></script>
</body>
</html>